let lang = [
  ['Java', 'System.out.printl( "Hello World" )', 'B/F'],
  ['JavaScript', 'console.log( "Hello World" )', 'F'],
  ['Python', 'print( "Hello World" )', 'B/F'],
  ['Swift', 'print( "Hello World" )', 'F'],
  ['C++', 'cout << "Hello World"', 'F'],
  ['C#', 'Console.WriteLine( "Hello World" )', 'F'],
  ['Ruby', 'puts "Hello World"', 'B'],
  ['Visual Basic', 'Console.WriteLine( "Hello World" )', 'F'],
  ['PHP', 'N/A', 'B'],
  ['Assembly', 'msg db "Hello World"', 'B'],
  ['Go', 'fmt.Printf( "Hello World" )', 'B'],
  ['C', 'printf( "Hello World" )', 'F'],
  ['Objective C', 'NSLog(@"Hello World" )', 'F'],
  ['Matlab', 'disp( "Hello World" )', 'F'],
  ['Typescript', 'console.log( "Hello World" )', 'F'],
  ['Kotlin', 'Log.d( "Hello World" )', 'F'],
  ['VBA', 'MsgBox "Hello World"', 'B'],
  ['Bash', 'echo "Hello World"', 'F'],
  ['Curl', 'N/A', 'B'],
  ['Delphi', 'Label1.Caption := "Hello World"', ''],
  ['ECMAScript', 'console.log( "Hello World" )', 'F'],
  ['PL/SQL', 'dbms_output.put_line( "Hello World" )', 'B'],
  ['JavaFX', 'System.out( "Hello World" )', 'F'],
  ['JScript', 'print( "Hello World" )', 'B/F'],
  ['XML', 'N/A', 'F'],
  ['HTML', 'N/A', 'F'],
  ['CSS', 'N/A', 'F'],
  ['JQuery', 'N/A', 'F']
]
