let lang = [
  ['Michael Jackson', 'M', 'died in 2009', 'Michael Jackson, also known as the King of pop performed exactly 4 times in Vienna (Austria). He was considered the most famous musician of all time.'],
  ['Justin Bieber', 'M/I', '23', 'Well.. what should i say.. you know him...'],
  ['George Clooney', 'S', '56', 'What else? George Clooney is not only famous for his Nespresso Advertisment, he is also a great actor, which made a lot of films better due to his appereance.'],
  ['Dwayne Johnson', 'S', '45', "Probably the best known rock of all time. Also a great actor. Let's wait  for his new movie 'Jumanji'."],
  ['Harrison Ford', 'S', '75', 'The man, the myth, the legend.. Han Solo!'],
  ['Tom Hanks', 'S', '61', 'Not only a great actor, also a superb comedian.'],
  ['Scarlett Johansson', 'S', '33', "The hottest 'Black Widow' there could ever be. She's an Avenger.. nothing more to say."],
  ['Angelina Jolie', 'S', '42', "The actress, which made 'Mr. & Mrs. Smith' famous. She also does tons of voluntary work"],
  ['Jennifer Aniston', 'S', '48', "'We are the Millers', 'Kill the Boss', ... There are many enjoyable films with this actress."],
  ['Jennifer Lawrence', 'S', '27', 'Katniss is not only famous for her role in The Hunger Games.. Let us not forget about the Fappening..'],
  ['Tom Cruise', 'S', '55', "Mission Impossible's Star might not be the tallest actor, but he has some serious skills. Also he does most of his stunts on his own."],
  ['Brad Pitt', 'S', '53', "Mr. Smith.. "],
  ['Nicholas Cage', 'S', '53', "Nicholas Cage has been a meme for quite some time now."],
  ['Will Smith', 'S', '49', 'I. am. Legend.'],
  ['Barack Obama', 'P', '56', 'The first black president of the United States of America'],
  ['Donald Trump', 'P', '71', 'Should cut his hair..'],
  ['Alexander van der Bellen', 'P', '73', ''],
  ['Sebastian Kurz', 'P', '31', ''],
  ['Angela Merkel', 'P', '63', ''],
  ['Elton John', 'M', '70', 'Likes candles in the wind'],
  ['David Guetta', 'M', '50', 'David Baguetta - think of it lol.'],
  ['Ed Sheeran', 'M', '26', 'Builds castles on the hill.'],
  ['Taylor Swift', 'M', '27', 'Taylor Swift likes to Shake it off!'],
  ['Angus Young', 'M', '62', ''],
  ['Brian Johnson', 'M', '70', ''],
  ['Phil Collins', 'M', '66', 'Eye of the Tiger!'],
  ['Shawn Mendes', 'M', '19', 'Nothing is holding him back.'],
  ['Selena Gomez', 'M', '25', 'Has quite a nice personality.'],
  ['Ariana Grande', 'M', '24', 'Does some fucked up music videos but is still a pretty young lady.'],
  ['Harry Styles', 'M', '23', 'Searches for signs of the time.'],
  ['Bruno Mars', 'M', '32', "I think he want's to merry me."]
]
